Update Whiskey.md
devrel-kr/HackaLearn pull request #178
Opened 2021-08-13 10:53 UTC by Lee-WonJun

> 각 **챌린지 미션**을 완료 할때 마다 **각자 자신의 항목을 수정하는** PR을 생성해 주세요.

## 챌린저 정보 ##

챌린저의 정보를 아래에 남겨주세요.

* 팀 이름:  Whiskey

> Microsoft Learn 프로필 URL은 `https://docs.microsoft.com/ko-kr/users/******`와 같이 생겼습니다.

* Microsoft Learn 프로필 URL:  wonjunlee-4989
* GitHub ID: @Lee-WonJun

아래는 SNS 챌린지의 경우에만 입력해 주세요.

> 다양한 SNS가 있지만, 여기서는 트위터, 페이스북, 인스타그램만 인정합니다.

* SNS 이름:
* SNS ID:

## 완료된 챌린지 ##

> 이번에 완료된 챌린지의 내용을 마킹해주세요.

* [x] 애저 정적 웹 앱 챌린지 완료
* [x] 깃헙 액션 챌린지 완료
* [ ] 소셜미디어 인증샷 챌린지 완료
* [ ] 애저 정적 웹 앱 URL 제출 챌린지 완료
* [ ] 애저 정적 웹 앱 리포지토리 제출 챌린지 완료
* [ ] 블로그 후기 URL 제출 챌린지 완료

2021-08-13 14:51 UTC, justinyoo requested changes
라인 20 혹은 34 둘 중 하나만 남겨두시고 PR을 수정해 주세요.

2021-08-13 14:51 UTC, justinyoo commented on teams/Whiskey.md
> +| [@Lee-WonJun](https://github.com/Lee-WonJun) | [스크린샷](https://user-images.githubusercontent.com/10369528/129346169-d909d24b-829a-40ff-9281-c364b1d8cf44.png) |
이 챌린지 PR이 애저 정적 웹 앱 챌린지에 대한 것이라면 이 부분을 남겨 두시고, 라인 34를 지워주세요. 둘 중 하나만 있어야 합니다.

2021-08-13 14:51 UTC, justinyoo commented on teams/Whiskey.md
> +| [@Lee-WonJun](https://github.com/Lee-WonJun) | [스크린샷](https://user-images.githubusercontent.com/10369528/129346213-b9500c05-0674-4399-b08e-42da9694ff95.png) |
이 챌린지 PR이 깃헙 액션 챌린지에 대한 것이라면 이 부분을 남겨 두시고, 라인 20을 지워주세요. 둘 중 하나만 있어야 합니다.

2021-08-13 17:21 UTC, jung-youjin commented
@Lee-WonJun 안녕하세요! 챌린지 완료해주셔서 감사합니다~! 😎👍🏼 **PR 당 하나의 챌린지에 대해서만 업데이트가 되어야합니다!** 따라서 저스틴님 Comment대로, 하나의 PR에 대한 변경사항만 남겨주시고, 그 다음 챌린지에 대한 PR은 나중에 새로 생성해주세요!  🙆🏼‍♀️

2021-08-14 14:02 UTC, jung-youjin commented
@Lee-WonJun PR메시지에 Microsoft Learn URL 예시처럼 `https://docs.microsoft.com/ko-kr/users/wonjunlee-4989` 수정 부탁드립니다! 수정해주시면 바로 accept할게요🤗💪🏻

2021-08-14 15:26 UTC, Lee-WonJun commented
@jung-youjin 수정했습니다

2021-08-14 15:42 UTC, jung-youjin commented
> @jung-youjin 수정했습니다

감사합니다! 😁

2021-08-14 15:43 UTC, jung-youjin commented
/aswasignoff

2021-08-14 15:43 UTC, merged