Update 생생한국통.md
devrel-kr/HackaLearn pull request #197
Opened 2021-08-14 10:43 UTC by hyungraelee

> 각 **챌린지 미션**을 완료 할때 마다 **각자 자신의 항목을 수정하는** PR을 생성해 주세요.

## 챌린저 정보 ##

챌린저의 정보를 아래에 남겨주세요.

* 팀 이름: 생생한국통

> Microsoft Learn 프로필 URL은 `https://docs.microsoft.com/ko-kr/users/******`와 같이 생겼습니다.

* Microsoft Learn 프로필 URL: https://docs.microsoft.com/ko-kr/users/42015101/
* GitHub ID: @hyungraelee

아래는 SNS 챌린지의 경우에만 입력해 주세요.

> 다양한 SNS가 있지만, 여기서는 트위터, 페이스북, 인스타그램만 인정합니다.

* SNS 이름: 
* SNS ID: 

## 완료된 챌린지 ##

> 이번에 완료된 챌린지의 내용을 마킹해주세요.

* [x] 애저 정적 웹 앱 챌린지 완료
* [x] 깃헙 액션 챌린지 완료
* [ ] 소셜미디어 인증샷 챌린지 완료
* [ ] 애저 정적 웹 앱 URL 제출 챌린지 완료
* [ ] 애저 정적 웹 앱 리포지토리 제출 챌린지 완료
* [ ] 블로그 후기 URL 제출 챌린지 완료

2021-08-14 13:14 UTC, jung-youjin requested changes
PR 당 하나의 챌린지에 대한 업데이트가 되어야합니다! 이에 필요한 약간의 수정 사항들 반영 부탁드립니다 🙏🏼🛠

2021-08-14 13:14 UTC, jung-youjin commented on teams/생생한국통.md
> +| [@hyungraelee](https://github.com/hyungraelee) | [image](https://user-images.githubusercontent.com/70879607/129443297-5b797465-5d5a-4dc8-81ab-4378757c73f9.png) |
@hyungraelee 안녕하세요! **하나의 PR당 하나의 챌린지**에 대한 업데이트만 이루어져야 합니다! PR 내용을 애저정적웹앱에만 체크✅로 수정해주시고, Line 21만 남기도 나머지 부분은 제외해주시고 깃헙액션 부분에 대한 PR은 새로 만들어주세요 😊🙏🏼

2021-08-14 13:14 UTC, jung-youjin commented on teams/생생한국통.md
> +| [@hyungraelee](https://github.com/hyungraelee) | [image](https://user-images.githubusercontent.com/70879607/129443366-12118a5e-19db-4348-b4e8-a1703995e5f7.png) |
@hyungraelee 깃헙액션에 대한 링크는 이번 PR에서 원상복구 해주신 후, 새로운 PR에 추가해주세요!🙆🏼‍♀️👍🏼

2021-08-15 09:08 UTC, hyungraelee commented
PR 당 하나의 챌린지로 수정 하였습니다! 확인 해주세요!

2021-08-15 11:39 UTC, jung-youjin commented
@hyungraelee 수정 반영 감사합니다! 그런데, 올려주신 스크린샷이 깃헙액션쪽으로 뜨는 것 같습니다! 혹시 확인 후 스크린샷 재제출 가능하실까요? 감사합니다!!🙏🏼🤗

2021-08-15 11:45 UTC, hyungraelee commented
@jung-youjin  스크린샷 링크 수정했습니다!😅 감사합니다!

2021-08-15 12:11 UTC, jung-youjin commented
> @jung-youjin 스크린샷 링크 수정했습니다!😅 감사합니다!

@hyungraelee 빠른 수정 감사합니다!! 확인했습니다😎👍🏼 8/16 0시 기준으로 PR 새로 생성된 제출은 마감되니 이 점 유의하여서 제출 부탁드려요! 감사합니다

2021-08-15 12:12 UTC, jung-youjin commented
/aswasignoff

2021-08-15 12:13 UTC, merged