Add CODE-OF-CONDUCT.md PRIVACY-POLICY.md
devrel-kr/HackaLearn pull request #2
Opened 2021-07-02 16:53 UTC by jung-youjin

Both files are still drafts, these need thorough review.

2021-07-05 02:57 UTC, justinyoo requested changes
잘 만드셨습니다! 몇 가지 자잘한 것들만 수정하시면 될 것 같아요. 확인하고 수정 부탁드립니다!

2021-07-05 02:57 UTC, justinyoo commented on CODE-OF-CONDUCT.md
> +### ✔ 서약
요기는 ## 두개로 해서 H2 레벨 헤더로 바꿔 주세요. 요 밑에 것들도 함께요.

2021-07-05 02:57 UTC, justinyoo commented on PRIVACY-POLICY.md
> +### ✔ 개인정보 수집
여기도 ## 두개로 맞춰 주세욥

2021-07-05 02:57 UTC, justinyoo commented on PRIVACY-POLICY.md
> +- 파기절차
여기서 - (리스트) 대신 ### 로 해서 H3 헤더로 맞추는게 좋은 것 같습니다. 어떻게 생각하세요?

2021-07-06 12:45 UTC, jung-youjin commented on PRIVACY-POLICY.md
> +- 파기절차
좋습니다!! 수정해서 반영하겠습니다 🙏🏼

2021-07-06 12:46 UTC, jung-youjin commented on CODE-OF-CONDUCT.md
> +### ✔ 서약
네 알겠습니당!

2021-07-06 12:46 UTC, jung-youjin commented on PRIVACY-POLICY.md
> +### ✔ 개인정보 수집
넵!! 감사합니다

2021-07-06 15:35 UTC, jung-youjin commented
Apply reviews

2021-07-06 15:37 UTC, jung-youjin commented
Apply reviews

2021-07-06 15:37 UTC, merged