challenge 1, 2
devrel-kr/HackaLearn pull request #290
Opened 2021-08-15 08:58 UTC by thursdaydreaming

> 각 **챌린지 미션**을 완료 할때 마다 **각자 자신의 항목을 수정하는** PR을 생성해 주세요.

## 챌린저 정보 ##

챌린저의 정보를 아래에 남겨주세요.

* 팀 이름: godlife

> Microsoft Learn 프로필 URL은 `https://docs.microsoft.com/ko-kr/users/******`와 같이 생겼습니다.

* Microsoft Learn 프로필 URL: https://docs.microsoft.com/ko-kr/users/godlife
* GitHub ID: @thursdaydreaming

아래는 SNS 챌린지의 경우에만 입력해 주세요.

> 다양한 SNS가 있지만, 여기서는 트위터, 페이스북, 인스타그램만 인정합니다.

* SNS 이름:
* SNS ID:

## 완료된 챌린지 ##

> 이번에 완료된 챌린지의 내용을 마킹해주세요.

* [ ] 애저 정적 웹 앱 챌린지 완료
* [ ] 깃헙 액션 챌린지 완료
* [ ] 소셜미디어 인증샷 챌린지 완료
* [ ] 애저 정적 웹 앱 URL 제출 챌린지 완료
* [ ] 애저 정적 웹 앱 리포지토리 제출 챌린지 완료
* [ ] 블로그 후기 URL 제출 챌린지 완료

2021-08-15 10:52 UTC, jung-youjin requested changes
**하나의 PR당 하나의 챌린지**만 업데이트 되어야합니다. 이에 필요한 수정사항 comment를 남겼으니 리뷰 확인 후 수정 부탁드립니다!! 😎 😮

2021-08-15 10:52 UTC, jung-youjin commented on teams/godlife.md
> +| [@thursdaydreaming](https://github.com/thursdaydreaming) | https://user-images.githubusercontent.com/42180969/129472954-6bbe6d58-b712-4af9-a5e7-0a5c5c932f29.png |
한 PR당 하나의 챌린지에 대한 변경사항만 업데이트 되어야합니다. 따라서, 요 부분만 남기고 나머지 line은 지워주세요!! 💯

2021-08-15 10:52 UTC, jung-youjin commented on teams/godlife.md
> +| [@thursdaydreaming](https://github.com/thursdaydreaming) |https://user-images.githubusercontent.com/42180969/129472936-962d8fcf-fc18-424d-ae4d-29f4d87dd1ad.png |
깃헙 액션 챌린지는 새로운 PR 만들어서 거기에 링크 추가해주세요! 이번 PR에서는 line 33 원상복구 부탁드립니다 🙏🏼

2021-08-15 14:46 UTC, jung-youjin commented
@thursdaydreaming Review 코멘트드린거 확인 부탁드립니다! 🙏🏼✅

2021-08-15 15:10 UTC, jung-youjin commented
@thursdaydreaming  8/16 0시 내로 제출해주신 PR이어서 리뷰 가능✅ 대상 PR입니다! 제출해주셔서 감사하고, 꼼꼼히 리뷰하겠습니다! PR Close하시면 이미 기한이 지나 새로운 PR 제출은 안되니, 유의하시고 절대 PR Close하지 말아주세요!👍🏼

2021-08-15 23:57 UTC, jung-youjin commented
@thursdaydreaming Conflict 수정해주시고 나면, **PR당 챌린지 1개** 원칙 때문에, 이번에는 Challenge 2를 제외한 Challenge 1에 대해서만 인정한 후 Merge 수락하겠습니다!  챌린지 완료해주셔서 감사합니다 😁🙏🏼

2021-08-16 01:34 UTC, thursdaydreaming commented
지금 수정이 가능할까요? ㅠㅠ 방금 해보니 시간이 지나서 안된다고...

2021-08-16 01:35 UTC, jung-youjin commented
@thursdaydreaming 현재 이 PR 내에서 수정은 가능합니다, 다만 새로운 PR 제출은 안돼요!😭

2021-08-16 01:35 UTC, thursdaydreaming commented
수정했습니다!

2021-08-16 01:37 UTC, jung-youjin commented
@thursdaydreaming 수정 감사합니다!👍🏼 애저 정적 웹 앱 클라우드 스킬 챌린지 부분만 수락하고 Merge하겠습니다! 고생 정말 많으셨습니다~😊🙏🏼

2021-08-16 01:38 UTC, jung-youjin commented
@thursdaydreaming 엇 Conflict 생기는데, 이 부분 수정 부탁드립니다! 아니면 Merge가 안되어서요ㅜㅜ!!

2021-08-16 01:55 UTC, thursdaydreaming commented
왜 컨플릭이 생기는 걸까요...?ㅠㅠ

2021-08-16 02:06 UTC, thursdaydreaming commented
왜...왜 컨플릭이 ㅠㅠㅠㅠㅠㅠ제가 사실 이 챌린지 이후에 동일한 내용으로 풀리퀘를 진행했는데 해당 파일에서 다시 수정해도 반영이 될까요,,

2021-08-16 02:55 UTC, justinyoo commented
@thursdaydreaming 만약 동일한 내용으로 풀리퀘 진행을 해서 이 PR이 필요없다고 판단하시면 종료하셔도 됩니다. 다만, 종료하신 후에는 새로 PR 생성이 안됩니다.

2021-08-16 03:16 UTC, closed without merging