정적 웹 앱 챌린지 및 깃헙 액션챌린지 완료
devrel-kr/HackaLearn pull request #322
Opened 2021-08-15 10:23 UTC by seonghun-dev

> 각 **챌린지 미션**을 완료 할때 마다 **각자 자신의 항목을 수정하는** PR을 생성해 주세요.

## 챌린저 정보 ##

챌린저의 정보를 아래에 남겨주세요.

* 팀 이름: Pub

> Microsoft Learn 프로필 URL은 `https://docs.microsoft.com/ko-kr/users/******`와 같이 생겼습니다.

* Microsoft Learn 프로필 URL: https://docs.microsoft.com/ko-kr/users/04310058/
* GitHub ID: @seonghun-dev

아래는 SNS 챌린지의 경우에만 입력해 주세요.

> 다양한 SNS가 있지만, 여기서는 트위터, 페이스북, 인스타그램만 인정합니다.

* SNS 이름:
* SNS ID:

## 완료된 챌린지 ##

> 이번에 완료된 챌린지의 내용을 마킹해주세요.

* [x] 애저 정적 웹 앱 챌린지 완료
* [x] 깃헙 액션 챌린지 완료
* [ ] 소셜미디어 인증샷 챌린지 완료
* [ ] 애저 정적 웹 앱 URL 제출 챌린지 완료
* [ ] 애저 정적 웹 앱 리포지토리 제출 챌린지 완료
* [ ] 블로그 후기 URL 제출 챌린지 완료

2021-08-15 12:23 UTC, u0jin commented
@seonghun-dev  PR하나당 하나의 챌린지만을 올려주세요:)

2021-08-15 13:47 UTC, u0jin commented
@seonghun-dev  file changed 를 보면 아직 수정되지않았다고 보여집니다.

2021-08-15 14:14 UTC, u0jin commented
@seonghun-dev  file changed 가 수정되지않았습니다. 하나의 PR에는 하나의 챌린지만 올려주세요

2021-08-15 14:33 UTC, u0jin commented
@seonghun-dev  PR하나당 하나의 챌린지만 올려주세요:)

2021-08-15 14:40 UTC, justinyoo requested changes
현재 올려주신 PR은 본인의 애저 정적 웹 앱 챌린지에 대한 내용만 리뷰합니다. 타 팀원 챌린지는 각자 PR을 생성해서 올리라고 안내해 주시구요, @seonghun-dev 님의 다른 챌린지는 이 PR이 아니라 깃헙 액션 챌린지 PR, SNS 챌린지 PR, 블로그 챌린지 PR을 별도로 생성해서 올려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@judemin](https://github.com/judemin) | https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/IMG_0033.png?raw=true |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@eanshu](https://github.com/eanshu) | https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/IMG_1887.jpeg?raw=true |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@seonghun-dev](https://github.com/seonghun-dev) | https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/Azure%20static%20web%20App_seonghun.png?raw=true |
이 PR에서는 이 내용 하나만 리뷰합니다. 나머지 내용은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@seonghun-dev](https://github.com/seonghun-dev) | https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/Github%20Action_seonghun.png?raw=true|
이 PR에서는 이 내용을 리뷰하지 않습니다. 여긴 원래대로 돌려주시고 새 PR로 이 깃헙 액션 챌린지 부분을 올려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@judemin](https://github.com/judemin) | https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/IMG_0034.png?raw=true|
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@eanshu](https://github.com/eanshu) |https://github.com/seonghun-dev/seonghun-dev.github.io/blob/main/images/Hackelarn/IMG_1887.jpeg?raw=true  |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@judemin](https://github.com/judemin) | https://www.instagram.com/p/CSmMiEXBRNz/?utm_source=ig_web_copy_link |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@eanshu](https://github.com/eanshu) | https://www.instagram.com/p/CSmOLwuFddL/?utm_source=ig_web_copy_link |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@judemin](https://github.com/judemin) | https://nickel-quarter-02b.notion.site/147324a047b148118ba0c5f0fa1baaac |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@eanshu](https://github.com/eanshu) |  |
다른 팀원은 해당 팀원이 직접 PR을 올리셔야 합니다. 이 부분은 원래대로 돌려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@seonghun-dev](https://github.com/seonghun-dev) | https://www.instagram.com/p/CSmLGaOBVmy/?utm_medium=copy_link |
이 PR에서는 이 내용을 리뷰하지 않습니다. 여긴 원래대로 돌려주시고 새 PR로 이 SNS 챌린지 부분을 올려주세요.

2021-08-15 14:40 UTC, justinyoo commented on teams/Pub.md
> +| [@seonghun-dev](https://github.com/seonghun-dev) | https://velog.io/@seonghun-dev/HackaLearn-참여-후기 |
이 PR에서는 이 내용을 리뷰하지 않습니다. 여긴 원래대로 돌려주시고 새 PR로 이 블로그 후기 챌린지 부분을 올려주세요.

2021-08-15 15:09 UTC, jung-youjin commented
@seonghun-dev  8/16 0시 내로 제출해주신 PR이어서 리뷰 가능✅ 대상 PR입니다! 제출해주셔서 감사하고, 꼼꼼히 리뷰하겠습니다! PR Close하시면 이미 기한이 지나 새로운 PR 제출은 안되니, 유의하시고 절대 PR Close하지 말아주세요!👍🏼

2021-08-16 00:02 UTC, jung-youjin commented
@seonghun-dev Review Comment 대로 수정 부탁드립니다! 이번 PR은 **클라우드 스킬 챌린지 1. 애저 정적 웹앱** 부분 만 인정됩니다!✅👍🏼

2021-08-16 02:40 UTC, jung-youjin commented
@seonghun-dev **SNS 챌린지** 부분 만 승인되어 Merge합니다! 감사합니다~🙏🏼

2021-08-16 02:40 UTC, jung-youjin commented
/socialsignoff

2021-08-16 02:41 UTC, merged