Feature/update readme
devrel-kr/HackaLearn pull request #364
Opened 2021-08-15 13:31 UTC by yoonminsohappy

> 각 **챌린지 미션**을 완료 할때 마다 **각자 자신의 항목을 수정하는** PR을 생성해 주세요.

## 챌린저 정보 ##

챌린저의 정보를 아래에 남겨주세요.

* 팀 이름: 

> Microsoft Learn 프로필 URL은 `https://docs.microsoft.com/ko-kr/users/******`와 같이 생겼습니다.

* Microsoft Learn 프로필 URL:  https://docs.microsoft.com/ko-kr/users/yoonmincho-4760/
* GitHub ID: @yoonminsohappy 

아래는 SNS 챌린지의 경우에만 입력해 주세요.

> 다양한 SNS가 있지만, 여기서는 트위터, 페이스북, 인스타그램만 인정합니다.

* SNS 이름:
* SNS ID:

## 완료된 챌린지 ##

> 이번에 완료된 챌린지의 내용을 마킹해주세요.

* [ ] 애저 정적 웹 앱 챌린지 완료
* [ ] 깃헙 액션 챌린지 완료
* [ ] 소셜미디어 인증샷 챌린지 완료
* [ ] 애저 정적 웹 앱 URL 제출 챌린지 완료
* [x] 애저 정적 웹 앱 리포지토리 제출 챌린지 완료
* [ ] 블로그 후기 URL 제출 챌린지 완료

2021-08-15 14:39 UTC, yoonminsohappy commented
@jung-youjin 리뷰와 머지 부탁드립니다!

2021-08-15 14:45 UTC, yoonminsohappy commented
@justinyoo 리뷰 부탁드립니다 :)

2021-08-15 15:08 UTC, jung-youjin commented
@yoonminsohappy  8/16 0시 내로 제출해주신 PR이어서 **리뷰 가능✅** 대상 PR입니다! 제출해주셔서 감사하고, 꼼꼼히 리뷰하겠습니다! **PR Close하시면 이미 기한이 지나 새로운 PR 제출은 안되니, 유의하시고 절대 PR Close하지 말아주세요!👍🏼**
- Repository 챌린지의 경우 저희가 직접 로컬에서 테스트해봐야해서 시간이 조금 소요되어요! 8/16 오후 12시까지 마무리한 후 리뷰 마무리하겠습니다!

2021-08-15 23:53 UTC, jung-youjin requested changes
@yoonminsohappy `teams/ExcelGirls.md` 파일에 나머지 라인들 `devrel-kr:main`에서 머지하신 후 다시 수정 부탁드려도 될까요? 저렇게 repo-challenge를 제외한 다른 부분들이 **비어있으면 안되고** 현재 `devrel-kr:main` 브랜치와 동일하게 링크가 기입되어있는 상태여야합니다. 지금 상태로 Merge 하게 되면, 지금까지 올려주신 다른 챌린지 링크들이 제일 최신 상태로 반영되어 지금 수정해주신 것 처럼 다 사라져요!ㅜㅜ😭🙏🏼

2021-08-15 23:53 UTC, jung-youjin commented on teams/ExcelGirls.md
> +| [@yoonminsohappy](https://github.com/yoonminsohappy) | _링크를 남겨주세요_ |
`devrel-kr:main` 브랜치에서 fetch하신 후 작업 부탁드립니다. 링크를 지워주시게 되면 전에 하신 링크가 사라지게 됩니다!

2021-08-15 23:53 UTC, jung-youjin commented on teams/ExcelGirls.md
> +| [@yoonminsohappy](https://github.com/yoonminsohappy) | ""                  |
마찬가지로 `devrel-kr:main` 브랜치에서 fetch하신 후 작업 부탁드립니다. 링크를 지워주시게 되면 전에 하신 링크가 사라지게 됩니다!

2021-08-15 23:53 UTC, jung-youjin commented on teams/ExcelGirls.md
> +| 깃헙 리포지토리 | _링크를 남겨주세요_                                   |
이번 챌린지가 
- **애저 정적 웹 앱 리포지토리 챌린지**라면 **깃헙리포지토리** 항목이 GitHub Repository 항목으로 채워져야하고,
- **애저 정적 웹 앱 URL 챌린지** 라면 **애저 정적 웹 앱** 항목이 **~~.azurestaticapps.net**으로 채워져야합니다.
PR 메세지에는 **애저 정적 웹 앱 리포지토리 챌린지** 라고 되어있는데, 이 부분이 비어있네요! 확인 부탁드립니다.😊

2021-08-16 00:00 UTC, jung-youjin commented
## ExcelGirls 팀 남은 챌린지 리스트
- 애저 정적 웹 앱 리포지토리 챌린지
- 애저 정적 웹 앱 URL 챌린지
- 블로그 후기 챌린지
---
3가지 중 하나만 선택하여 이번 PR 수정해주시면 바로 Merge 리뷰하겠습니다! 감사합니다.😊🙏🏼

2021-08-16 01:44 UTC, jung-youjin commented on teams/ExcelGirls.md
> +| 깃헙 리포지토리 | _링크를 남겨주세요_                                   |
@yoonminsohappy `https://thankful-rock-07ed1dc10.azurestaticapps.net` 링크 또한 사이트 배포가 제대로 안 이루어진 것 같습니다. 확인 가능하실까요? 🙏🏼

2021-08-16 03:16 UTC, closed without merging

2021-08-17 00:30 UTC, yoonminsohappy commented on teams/ExcelGirls.md
> +| 깃헙 리포지토리 | _링크를 남겨주세요_                                   |
어엇 네네! 확인 해보겠습니다!