Upload banners and modify banner sizes
devrel-kr/HackaLearn pull request #5
Opened 2021-07-08 15:25 UTC by jung-youjin

2021-07-09 02:40 UTC, justinyoo requested changes
좋습니다! 다만,

* 파일 이름을 한글명에서 영문명으로 바꾸면 좋아요. 아직까지 한글 파일명을 제대로 처리 못하는 경우가 많으니;;;
* 이미지 크기는 아래 리뷰 코멘트에서 말씀드린대로 원래 크기 그대로 가면 좋습니다. 그러면 이미지가 확실히 선명하게 보여요.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template-1.html
> +                                  <img id="banner" alt height="auto" src="../banners/등록확인.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
파일 이름을 영문으로 할까요? `confirm-registration` 그리고 `width="600"` 으로 동일하게 하면, 같은 사이즈에서 이미지가 더 쨍하게 보이는 효과가 있음.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template-2.html
> +                                  <img id="banner" alt height="auto" src="../banners/제출독려.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
파일 이름을 영문으로 할까요? `keep-it-up` 그리고 `width="600"` 으로 동일하게 하면, 같은 사이즈에서 이미지가 더 쨍하게 보이는 효과가 있음.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template-3.html
> +                                  <img id="banner" alt height="auto" src="../banners/제출진행상황.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;
파일 이름을 영문으로 할까요? `work-in-progress` 그리고 `width="600"` 으로 동일하게 하면, 같은 사이즈에서 이미지가 더 쨍하게 보이는 효과가 있음.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template-4.html
> +                                  <img id="banner" alt height="auto" src="../banners/최종제출.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
파일 이름을 영문으로 할까요? `confirm-submission` 그리고 `width="600"` 으로 동일하게 하면, 같은 사이즈에서 이미지가 더 쨍하게 보이는 효과가 있음.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template-5.html
> +                                  <img id="banner" alt height="auto" src="../banners/축하합니다.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
파일 이름을 영문으로 할까요? `congrats` 그리고 `width="600"` 으로 동일하게 하면, 같은 사이즈에서 이미지가 더 쨍하게 보이는 효과가 있음.

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-1" src="../banners/등록확인.png">
위에서 말씀드린 대로 파일 이름 바꾸시지요! 그리고 `width="450"` 으로 동일하게

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-2" src="../banners/제출독려.png">
위에서 말씀드린 대로 파일 이름 바꾸시지요! 그리고 `width="450"` 으로 동일하게

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-3" src="../banners/제출진행상황.png">
위에서 말씀드린 대로 파일 이름 바꾸시지요! 그리고 `width="450"` 으로 동일하게

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-4" src="../banners/최종제출.png">
위에서 말씀드린 대로 파일 이름 바꾸시지요!

2021-07-09 02:40 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-5" src="../banners/축하합니다.png">
위에서 말씀드린 대로 파일 이름 바꾸시지요! 그리고 `width="450"` 으로 동일하게

2021-07-10 06:44 UTC, jung-youjin commented on templates/email/email-template-1.html
> +                                  <img id="banner" alt height="auto" src="../banners/등록확인.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
넵!
-[x] confirm-registration.png 로 변경
-[x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template-1.html
> +                                  <img id="banner" alt height="auto" src="../banners/등록확인.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
넵!
- [x] confirm-registration.png 로 변경
- [x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template-2.html
> +                                  <img id="banner" alt height="auto" src="../banners/제출독려.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
넵!
- [x] keep-it-up.png 로 변경
- [x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template-3.html
> +                                  <img id="banner" alt height="auto" src="../banners/제출진행상황.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;
넵!
- [x] work-in-progress.png 로 변경
- [x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template-4.html
> +                                  <img id="banner" alt height="auto" src="../banners/최종제출.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
넵!
- [x] confirm-submission.png 로 변경
- [x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template-5.html
> +                                  <img id="banner" alt height="auto" src="../banners/축하합니다.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;"
넵!
- [x] congrats.png 로 변경
- [x] width=1500(원본 이미지 사이즈)로 변경

2021-07-10 06:57 UTC, jung-youjin commented on templates/email/email-template.md
> +<img width="1500" alt="banner-1" src="../banners/등록확인.png">
원본이미지가 1500*500px인데, `email-template.md`에서만 `width="450"`으로 설정하면 될까요?

2021-07-10 15:02 UTC, justinyoo requested changes
좋습니다! 이미자 파일의 width 값을 예전대로 돌려주세요. 이 부분이 무슨 말인지 이해가 안가면 다시 알려주세요.

2021-07-10 15:02 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-1" src="../banners/confirm-registration.png">
width 값이 여전히 1500이네요? 원래대로 450으로 바꿔주세요.

2021-07-10 15:02 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-2" src="../banners/keep-it-up.png">
width 값이 여전히 1500이네요? 원래대로 450으로 바꿔주세요.

2021-07-10 15:02 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-3" src="../banners/work-in-progress.png">
width 값이 여전히 1500이네요? 원래대로 450으로 바꿔주세요.

2021-07-10 15:02 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-4" src="../banners/confirm-submission.png">
width 값이 여전히 1500이네요? 원래대로 450으로 바꿔주세요.

2021-07-10 15:02 UTC, justinyoo commented on templates/email/email-template.md
> +<img width="1500" alt="banner-5" src="../banners/congrats.png">
width 값이 여전히 1500이네요? 원래대로 450으로 바꿔주세요.

2021-07-11 02:11 UTC, justinyoo commented
@jung-youjin 혹시 이미지 사이즈 관련해서 제 리뷰 코멘트가 이해가 안가신다면, 아래와 같이 바꿔주시면 됩니다.

> 이 코멘트는 오직 이미지 사이즈 변경에 대해서"만" 언급하는 거예요. 그 이외의 내용은 위 PR 에서 다 변경하셨어요.

* 최상단 HackaLearn 배너 이미지
    ![](https://user-images.githubusercontent.com/37402072/124597776-d5513480-de9e-11eb-9ad5-1ca63686bd9b.JPG)
  * 현재 사이즈: 734x347 👉 변경 사이즈: 1200x400
  * 만약 이 이미지 말고 다른 것 쓰고 싶으면 다른 것으로 바꿔도 됩니다. (예를 들어 우리 README.md 페이지에 있는 걸로 바꿔도 됨)
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 애니메이션 gif
    ![](https://user-images.githubusercontent.com/37402072/124596926-cae26b00-de9d-11eb-8ee8-fb9db0ee4109.gif)
  * 현재 사이즈: 400x300 👉 변경 사이즈: 600x450 또는 1200x900
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 메인 배너 이미지 1
    ![](https://user-images.githubusercontent.com/37402072/124601175-7e4d5e80-dea2-11eb-98b7-0bbdec7fb42f.png)
  * 현재 사이즈: 600x200 👉 변경 사이즈: 1200x400
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 메인 배너 이미지 2
    ![](https://user-images.githubusercontent.com/37402072/124631830-b6fb3100-debe-11eb-8093-41727fddac3d.png)
  * 현재 사이즈: 900x300 👉 변경 사이즈: 1200x400
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 메인 배너 이미지 3
    ![](https://user-images.githubusercontent.com/37402072/124631844-ba8eb800-debe-11eb-9e3c-607d92b7d8d8.png)
  * 현재 사이즈: 900x300 👉 변경 사이즈: 1200x400
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 메인 배너 이미지 4
    ![](https://user-images.githubusercontent.com/37402072/124631851-be223f00-debe-11eb-9867-45521d081f2c.png)
  * 현재 사이즈: 900x300 👉 변경 사이즈: 1200x400
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

* 중간 메인 배너 이미지 5
    ![](https://user-images.githubusercontent.com/37402072/124631861-c11d2f80-debe-11eb-961c-7b156c522105.png)
  * 현재 사이즈: 900x300 👉 변경 사이즈: 1200x400
  * 그리고 HTML 태그 안의 속성은 계속 `width="600"` 으로 유지

2021-07-13 12:58 UTC, jung-youjin commented
@justinyoo 수정했습니다!!! 🙏🏼

2021-07-15 04:30 UTC, jung-youjin commented
1. 
![image](https://user-images.githubusercontent.com/37402072/125728699-b44e363c-6044-4283-8003-456ee38a3635.png)

2. 
![image](https://user-images.githubusercontent.com/37402072/125728829-ec7b9a61-9d18-417b-bd57-ece4fb495885.png)

3.
![image](https://user-images.githubusercontent.com/37402072/125729083-1c32c025-ef43-42d5-9258-d6b41839eef8.png)

@justinyoo 이메일 템플릿 위 상단에 들어가는 이미지만 확정 지으면 되는데 뭐가 좋을까욥?

2021-07-16 06:05 UTC, justinyoo approved these changes
좋습니다! 고생하셨쎄요! 👍👍👍👍👍

2021-07-16 06:06 UTC, justinyoo commented
> ![image](https://user-images.githubusercontent.com/37402072/125728699-b44e363c-6044-4283-8003-456ee38a3635.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/37402072/125728829-ec7b9a61-9d18-417b-bd57-ece4fb495885.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/37402072/125729083-1c32c025-ef43-42d5-9258-d6b41839eef8.png)
> 
> @justinyoo 이메일 템플릿 위 상단에 들어가는 이미지만 확정 지으면 되는데 뭐가 좋을까욥?
> 
> * 현재 상태는 2번입니다!

전 맨 위 1번이 좋아요. 최대한 얇게.

2021-07-16 06:06 UTC, merged